server:
  port: 8082
spring:
  config:
#    import:
#      - optional:oauth.yml
#      - optional:real-db.yml
#      - optional:file:/home/ec2-user/app/oauth.yml
#      - optional:file:/home/ec2-user/app/real-db.yml
    activate:
      on-profile: real2
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
