server:
  port: 8081
spring:
  config:
    activate:
      on-profile: real1
    import:
      - /home/ec2-user/app/oauth.yml
      - /home/ec2-user/app/real-db.yml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
