server:
  port: 8082
spring:
  config:
    activate:
      on-profile: real2
    import:
      - optional:oauth.yml
      - optional:real-db.yml
      - optional:/home/ec2-user/app/oauth.yml
      - optional:/home/ec2-user/app/real-db.yml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
