server:
  port: 8081
spring:
  config:
    activate:
      on-profile: real1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
  profiles:
    include:
      - optional:file:/home/ec2-user/app/oauth.yml
      - optional:file:/home/ec2-user/app/real-db.yml
