server:
  port: 8081
spring:
  config:
    import:
#      - /home/ec2-user/app/oauth.yml
#      - /home/ec2-user/app/real-db.yml
    activate:
      on-profile: real1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true

