spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect   # mysql식 쿼리로그찍기 위해 추가 스프링부트 버전에 따라 설정이 다름
  config:
    import:
      - oauth.yml
      - real-db.yml
  #Test OAuth test할 때 oauth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test
            client-secret: test
            scope:
              - profile
              - email
  profiles:
    group:
      default : oauth,real-db
      real1 : real1,oauth,real-db
      real2 : real2,oauth,real-db
  devtools:
    add-properties: true
